### PR TITLE
Changes done in navbar. 

### PR DESCRIPTION
**Pull request by Anushree176**

### CODE REVIEW

**Review by ac030540 — CHANGES_REQUESTED** [review]
Great work @Anushree176 !

There is one small change. The scroll which happens once a dropdown item is clicked doesn't work as expected. It hides the heading/title of the particular section. Addition of "js-scroll-trigger" class to the anchor tag of the dropdown links might solve the problem.

**Comment by Anushree176** [comment]
Thank you!
Deleted js-scroll-trigger class from anchor tags. Please review.

**Review by ac030540 — CHANGES_REQUESTED** [review]
Screenshot 2020-10-09 at 10 14 43 PM
In the previous implementation, when we were on a particular section then the nav item used to turn blue in color. However in your implementation, events in the navbar turns out blue when we are on workshops section but not in innovations and contests.

Screenshot 2020-10-09 at 10 09 53 PM
Screenshot 2020-10-09 at 10 09 44 PM
Glow on Event looks like a rectangle while on other links it is not the case.

**Comment by ac030540** [comment]
Closing for now!

**Pull request closed without merging**
